### PR TITLE
Toc - Add possibility to hide the page link

### PR DESCRIPTION
**Pull request by Nicolas-Git-13**
I need to display a toc like a word document. I only want the title link.
I use the attribute includeheadings to get the titles included in the toc. Therefore The level 1 of the toc are page link. This code add the attribute hidepagelink which hide the page link.
<doctoc includeheadings=1-5, hidepagelink=1>

### CODE REVIEW

**Comment by Nicolas-Git-13** [comment]
Usage Example:
`<doctoc includeheadings=1-5, onlyheadings=1>`
Sans titre

**Comment by Nicolas-Git-13** [comment]
Up

**Comment by Nicolas-Git-13** [comment]
There is few modification, could you have a look ?

**Comment by Klap-in** [comment]
I made some minor changes to working of the 'hidepagelink' option:
- Same way of recognizing on/off as other options
- if includeheadings is not set, set it to start=1,end=2.
- Make first heading=title strong, to recognize where a new page starts
- fix recursive check

**Comment by Klap-in** [comment]
Thanks for the idea and proposing it!

**Pull request merged**
