### PR TITLE
navigation compatibility with ckggedit

### PR DESCRIPTION
**Pull request by Nicolas-Git-13**
Add another tag to allow navigation compatibility with dokuwiki plugin ckgedit (https://www.dokuwiki.org/plugin:ckgedit)
Additionnal tag `<- prev ^ start ^ next >>` to complement existing `<- prev ^ start ^ next ->`

### CODE REVIEW

**Comment by Nicolas-Git-13** [comment]
Add the tag onlyheadings in the toc syntax to only displayed headings => Hiding page name

**Comment by Nicolas-Git-13** [comment]
<doctoc includeheadings=1-5, onlyheadings=1>

**Comment by Klap-in** [comment]
What is the meaning of `->` in the cgkedit plugin?

**Comment by Nicolas-Git-13** [comment]
Ckgedit is an editor to simplify dokuwiki editing.

`->` is transformed by `→` when the page is saved with ckgedit editor. Then the tag `<- prev ^ start ^ next ->` is not detected.

**Comment by Klap-in** [comment]
I propose the combination: << prev ^ start ^ next >> (with a symmetric syntax)

Please do 1 issue at a time.
I don't understand your proposal for `onlyheadings=1`
Could you maybe add an screenshot of the result before and after.

**Comment by Nicolas-Git-13** [comment]
I have changed the commit to have symetric syntax `<< prev ^ start ^ next >>`

**Comment by Nicolas-Git-13** [comment]
I need to print the table of content with only heading in all pages from the namespace. But it could have several title in each page, or no title.

For example I don't want that => the pages name are in bold (001_XXX, 002_XXX...). It is possible to replace the page name by the first title in the page but in this case, that duplicate this title in the table of content :

normal

I want that => get all title in every page and print it (onlyHeading option):

onlyHeading

**Pull request merged**
